In [58]:
import numpy as np
import pandas as pd

In [59]:
pd.Series(2)

0    2
dtype: int64

In [60]:
pd.Series('Philadelpia')

0    Philadelpia
dtype: object

In [61]:
series = pd.Series([1,2,3,4,5])
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [62]:
pd.Series(np.arange(1,5))

0    1
1    2
2    3
3    4
dtype: int32

In [63]:
pd.Series({1:'bolt', 2:'nut', 3:'pin'})

1    bolt
2     nut
3     pin
dtype: object

In [64]:
series = pd.series([1,2,3,4,5], index=['a','b','c','d','e'])
series

AttributeError: module 'pandas' has no attribute 'series'

In [ ]:
series.size

5

In [ ]:
len(series)

5

In [ ]:
series.shape

(5,)

In [ ]:
series.values

array([1, 2, 3, 4, 5], dtype=int64)

In [ ]:
series.loc[['a','c']]

a    1
c    3
dtype: int64

In [ ]:
series[0:3]

a    1
b    2
c    3
dtype: int64

In [ ]:
series.loc['a':'c']

a    1
b    2
c    3
dtype: int64

In [ ]:
series.iloc[2]

3

In [ ]:
series.iloc[2:]

c    3
d    4
e    5
dtype: int64

In [ ]:
series.iloc[-1]

5

In [ ]:
series1 = pd.Series([22,24,25])
series2 = pd.Series([40,56,24])
# df_from_series = pd.DataFrame({'age':series1, 'weight':series2})
df_from_series = pd.DataFrame([series1, series2])
df_from_series

0   1   2
0  22  24  25
1  40  56  24

In [ ]:
# df_from_series = pd.DataFrame([series1, series2], index=['age','weight'])
# df_from_series

0   1   2
age     22  24  25
weight  40  56  24

In [ ]:
# # df_from_series = pd.DataFrame([series1, series2], columns=['part1','part2','part3'])
# df_from_series = DataFrame.columns = ['part1','part2','part3']
# df_from_series

In [ ]:
df_from_dict = pd.DataFrame({'Part 1':series1, 'Part 2':series2, 'Part 3':[23,546,775]})
df_from_dict

Part 1  Part 2  Part 3
0      22      40      23
1      24      56     546
2      25      24     775

In [66]:
df_from_tup = pd.DataFrame([(2,4,6),(8,10,12),(4,5,6)], columns=['Part 1','Part 2','Part 3'])
df_from_tup

Part 1  Part 2  Part 3
0       2       4       6
1       8      10      12
2       4       5       6

In [70]:
df = pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0  0.675736 -0.529269 -0.759941 -0.909560
1  0.259590  1.752128 -0.221906 -0.357890
2  1.552929 -0.911244 -1.158206  0.844098
3  0.212263 -0.173976 -1.155826  1.221092
4  0.836970 -0.297631 -0.137380  1.126932

In [73]:
df = pd.DataFrame(np.random.randn(5,4), columns=list('ABCD'))
df

A         B         C         D
0 -1.436800  0.399777 -0.648157  0.794838
1  1.239147 -0.248957 -0.954302 -0.538134
2  0.867172 -0.460603 -0.024980 -0.419055
3 -1.581679  1.137261  0.083751  2.774316
4  0.872102  0.159081  0.918676  0.015553

In [74]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [75]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [76]:
df.values

array([[-1.43680046,  0.39977711, -0.64815677,  0.79483815],
       [ 1.23914683, -0.24895739, -0.95430163, -0.5381342 ],
       [ 0.86717189, -0.46060291, -0.02497969, -0.41905457],
       [-1.58167857,  1.13726064,  0.08375102,  2.77431603],
       [ 0.87210228,  0.15908088,  0.91867625,  0.01555318]])

In [77]:
df.head()

A         B         C         D
0 -1.436800  0.399777 -0.648157  0.794838
1  1.239147 -0.248957 -0.954302 -0.538134
2  0.867172 -0.460603 -0.024980 -0.419055
3 -1.581679  1.137261  0.083751  2.774316
4  0.872102  0.159081  0.918676  0.015553

In [78]:
df.tail()

A         B         C         D
0 -1.436800  0.399777 -0.648157  0.794838
1  1.239147 -0.248957 -0.954302 -0.538134
2  0.867172 -0.460603 -0.024980 -0.419055
3 -1.581679  1.137261  0.083751  2.774316
4  0.872102  0.159081  0.918676  0.015553

In [83]:
df.iloc[2:4]

A         B         C         D
2  0.867172 -0.460603 -0.024980 -0.419055
3 -1.581679  1.137261  0.083751  2.774316

In [82]:
df.iloc[2:4, 1:3]

B         C
2 -0.460603 -0.024980
3  1.137261  0.083751

In [84]:
df.iloc[2:4, [1,3]]

B         D
2 -0.460603 -0.419055
3  1.137261  2.774316

In [85]:
df.loc[2:4, ['A','C']]

A         C
2  0.867172 -0.024980
3 -1.581679  0.083751
4  0.872102  0.918676

In [86]:
df.transpose()

0         1         2         3         4
A -1.436800  1.239147  0.867172 -1.581679  0.872102
B  0.399777 -0.248957 -0.460603  1.137261  0.159081
C -0.648157 -0.954302 -0.024980  0.083751  0.918676
D  0.794838 -0.538134 -0.419055  2.774316  0.015553

In [87]:
df.T

0         1         2         3         4
A -1.436800  1.239147  0.867172 -1.581679  0.872102
B  0.399777 -0.248957 -0.460603  1.137261  0.159081
C -0.648157 -0.954302 -0.024980  0.083751  0.918676
D  0.794838 -0.538134 -0.419055  2.774316  0.015553

In [89]:
df[(df.A > 0) & (df.B > 0)]
# use df['A'] instead of df.A if column name has space or special characters

A         B         C         D
4  0.872102  0.159081  0.918676  0.015553

In [91]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [92]:
df['E'] = arr
df

A         B         C         D    E
0 -1.436800  0.399777 -0.648157  0.794838  1.0
1  1.239147 -0.248957 -0.954302 -0.538134  1.0
2  0.867172 -0.460603 -0.024980 -0.419055  1.0
3 -1.581679  1.137261  0.083751  2.774316  1.0
4  0.872102  0.159081  0.918676  0.015553  1.0

In [93]:
df.insert(2, 'F', arr)
df

A         B    F         C         D    E
0 -1.436800  0.399777  1.0 -0.648157  0.794838  1.0
1  1.239147 -0.248957  1.0 -0.954302 -0.538134  1.0
2  0.867172 -0.460603  1.0 -0.024980 -0.419055  1.0
3 -1.581679  1.137261  1.0  0.083751  2.774316  1.0
4  0.872102  0.159081  1.0  0.918676  0.015553  1.0

In [95]:
df.loc[:,'G'] = np.arange(11,16)
df

A         B    F         C         D    E   G
0 -1.436800  0.399777  1.0 -0.648157  0.794838  1.0  11
1  1.239147 -0.248957  1.0 -0.954302 -0.538134  1.0  12
2  0.867172 -0.460603  1.0 -0.024980 -0.419055  1.0  13
3 -1.581679  1.137261  1.0  0.083751  2.774316  1.0  14
4  0.872102  0.159081  1.0  0.918676  0.015553  1.0  15

In [101]:
df.loc[1:4,'J'] = np.arange(11,15)
df

A         B    F         C         D    E   G     J
0 -1.436800  0.399777  1.0 -0.648157  0.794838  1.0  11   NaN
1  1.239147 -0.248957  1.0 -0.954302 -0.538134  1.0  11  11.0
2  0.867172 -0.460603  1.0 -0.024980 -0.419055  1.0  12  12.0
3 -1.581679  1.137261  1.0  0.083751  2.774316  1.0  13  13.0
4  0.872102  0.159081  1.0  0.918676  0.015553  1.0  14  14.0

In [107]:
# axis=1 for column, axis=0 for row ?????????
df.drop('J', axis=1, inplace=True)
df

A         B         C         D    E   G
0 -1.436800  0.399777 -0.648157  0.794838  1.0  11
1  1.239147 -0.248957 -0.954302 -0.538134  1.0  11
2  0.867172 -0.460603 -0.024980 -0.419055  1.0  12
3 -1.581679  1.137261  0.083751  2.774316  1.0  13
4  0.872102  0.159081  0.918676  0.015553  1.0  14